version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
     - "3000:3000"
    volumes:
      - '/app/node_modules'
      - '.:/app'
  tests: # Tests service. Don't need ports.
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '/app/node_modules'
      - '.:/app'  
    command: ['npm', 'run', 'test']

# To run tests while running the main container:
# docker exec -it 1d604294693b npm run test